language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: O1r1FH3aRXTNhA4fHegQemNaRvGMwZ/nJjo6ajONF8Vkedk/k2K2JhfegsuvaxF4mmel/lQCGnpT5bidimfUUK+d1cstVaLQ7hE1ckyZ97OXfeF9UzQ8S9w/5ncPkWR1cvGuISoQ7/t/dLiOboRyppDOCexotQUZ6BKxSqsQv9+3NrJgXgbuYQsRrVJ/QPxHjgUvUXu1D7isdaiA/nAPQp+DeAnfjLbs/JTjvV1elVAh9QU3u6uWURdPLGeIjFtYghS8R+LJFuNZIGxykTYlXUtxnJGTwn2subXAgTpaPvgva2ybzcmx03Fp0LIShWkR1JfBYP0ixdcjDUJdDascHdAKqSDeAX3W4hAtcGyVwMxulqswc16+JQRd4eQUjOOQsx+z5UbO3CJAvo8OWVf3eN+KYW3Uw82IQzLrD+oQVIQfbLbCMeGYzuAV37QyjBldI3WB3ujetCkqbUW3Zpu1B+DdPkI5uOVrcHaDf+zqqRIVH7qLUqOJy2QtRBQM9/fWc6uHifDBA12pGzaUDjoLJdTi3vDC7EP1tMnaekk7c6lJIWcd5ssxXP8oEXy1AH3B7vipq+4WMma8CvVdfgMCVNy43NEWV+mDYzQ21Xu4vIoP7vBeqlDSlEYk1qkTrGz4+cwsE0WoqNjJHIFD8iuC2yQc/2UWkDWaGU53HiM3TIc=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: G8hoHgRxdqKnD6kzMJ+K38ouGKUE0nXALmtm1MeJwLqmfB5D2h0quUEKmkYXR6PtJSV+fYVc5/fmHEEmSoXBkphnqs0kXFRXBW46n52xxitAXGAZ5tObigAG6qM5RZ/iATIoeX2NgZjsWvt0Tfv2xPcW4H7GOZ4wTzO+kep1hyCEKd8t1GcAM/tFRIcjKRnYVZNQPnliflITFVKm0HnRv9QM9zL7DnkqOXwp6PCDaLBLkmawdjvbzpjpkR8LNy4odM0JKEgvcC+8EpYIhfmM8Trhn0msxrdNV/bCeyncOR+sEwdYwp9T48B/6yfVGpd8fVIig3xa8E6IQbc0HjzsTQjMN9ZMpzgywZH2cnFvtGqsIIg9fgIy5o6jilRNADvOEznOgnIiXNn5EWd8xierikQXWYjGdG5J+GawNbZPT2/SbnOjtWub04qpdEAxLcjQghXhjbl3/QakxP+n9VxC2/Su9gJw7K2U1CylhfJ1f5yBXdDGFfWMrHntnZ8KW5urR6z1I25yH4mJVi8klOHzMU0R8WLHkStc32pXugpYQfCeFCODXFNkaPbhd6HCYaLLZ+yK1nvD7hKfI1wb9g42m/cIT9W5OUyN+l0tccPfpMG6mr809z4Wb8e12PcypuckxMnUEQeCA3tEltWWcOs3zFL+0HvFbgShJDV6ZqdiKsY=
sudo: false
